/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.simulator.dto;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class SimulatorState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6934207490394410792L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SimulatorState\",\"namespace\":\"org.simulator.dto\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"isActive\",\"type\":\"boolean\"},{\"name\":\"isOccupied\",\"type\":\"boolean\"},{\"name\":\"components\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ComponentState\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"responseTime\",\"type\":\"int\"},{\"name\":\"temperature\",\"type\":\"int\"},{\"name\":\"power\",\"type\":\"int\"},{\"name\":\"voltage\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SimulatorState> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SimulatorState> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SimulatorState> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SimulatorState> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SimulatorState> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SimulatorState to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SimulatorState from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SimulatorState instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SimulatorState fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private String id;
  private boolean isActive;
  private boolean isOccupied;
  private java.util.List<org.simulator.dto.ComponentState> components;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SimulatorState() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param isActive The new value for isActive
   * @param isOccupied The new value for isOccupied
   * @param components The new value for components
   */
  public SimulatorState(String id, Boolean isActive, Boolean isOccupied, java.util.List<org.simulator.dto.ComponentState> components) {
    this.id = id;
    this.isActive = isActive;
    this.isOccupied = isOccupied;
    this.components = components;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return isActive;
    case 2: return isOccupied;
    case 3: return components;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: isActive = (Boolean)value$; break;
    case 2: isOccupied = (Boolean)value$; break;
    case 3: components = (java.util.List<org.simulator.dto.ComponentState>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'isActive' field.
   * @return The value of the 'isActive' field.
   */
  public boolean getIsActive() {
    return isActive;
  }


  /**
   * Sets the value of the 'isActive' field.
   * @param value the value to set.
   */
  public void setIsActive(boolean value) {
    this.isActive = value;
  }

  /**
   * Gets the value of the 'isOccupied' field.
   * @return The value of the 'isOccupied' field.
   */
  public boolean getIsOccupied() {
    return isOccupied;
  }


  /**
   * Sets the value of the 'isOccupied' field.
   * @param value the value to set.
   */
  public void setIsOccupied(boolean value) {
    this.isOccupied = value;
  }

  /**
   * Gets the value of the 'components' field.
   * @return The value of the 'components' field.
   */
  public java.util.List<org.simulator.dto.ComponentState> getComponents() {
    return components;
  }


  /**
   * Sets the value of the 'components' field.
   * @param value the value to set.
   */
  public void setComponents(java.util.List<org.simulator.dto.ComponentState> value) {
    this.components = value;
  }

  /**
   * Creates a new SimulatorState RecordBuilder.
   * @return A new SimulatorState RecordBuilder
   */
  public static org.simulator.dto.SimulatorState.Builder newBuilder() {
    return new org.simulator.dto.SimulatorState.Builder();
  }

  /**
   * Creates a new SimulatorState RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SimulatorState RecordBuilder
   */
  public static org.simulator.dto.SimulatorState.Builder newBuilder(org.simulator.dto.SimulatorState.Builder other) {
    if (other == null) {
      return new org.simulator.dto.SimulatorState.Builder();
    } else {
      return new org.simulator.dto.SimulatorState.Builder(other);
    }
  }

  /**
   * Creates a new SimulatorState RecordBuilder by copying an existing SimulatorState instance.
   * @param other The existing instance to copy.
   * @return A new SimulatorState RecordBuilder
   */
  public static org.simulator.dto.SimulatorState.Builder newBuilder(org.simulator.dto.SimulatorState other) {
    if (other == null) {
      return new org.simulator.dto.SimulatorState.Builder();
    } else {
      return new org.simulator.dto.SimulatorState.Builder(other);
    }
  }

  /**
   * RecordBuilder for SimulatorState instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SimulatorState>
    implements org.apache.avro.data.RecordBuilder<SimulatorState> {

    private String id;
    private boolean isActive;
    private boolean isOccupied;
    private java.util.List<org.simulator.dto.ComponentState> components;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.simulator.dto.SimulatorState.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.isActive)) {
        this.isActive = data().deepCopy(fields()[1].schema(), other.isActive);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.isOccupied)) {
        this.isOccupied = data().deepCopy(fields()[2].schema(), other.isOccupied);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.components)) {
        this.components = data().deepCopy(fields()[3].schema(), other.components);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SimulatorState instance
     * @param other The existing instance to copy.
     */
    private Builder(org.simulator.dto.SimulatorState other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isActive)) {
        this.isActive = data().deepCopy(fields()[1].schema(), other.isActive);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.isOccupied)) {
        this.isOccupied = data().deepCopy(fields()[2].schema(), other.isOccupied);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.components)) {
        this.components = data().deepCopy(fields()[3].schema(), other.components);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder setId(String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'isActive' field.
      * @return The value.
      */
    public boolean getIsActive() {
      return isActive;
    }


    /**
      * Sets the value of the 'isActive' field.
      * @param value The value of 'isActive'.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder setIsActive(boolean value) {
      validate(fields()[1], value);
      this.isActive = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'isActive' field has been set.
      * @return True if the 'isActive' field has been set, false otherwise.
      */
    public boolean hasIsActive() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'isActive' field.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder clearIsActive() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'isOccupied' field.
      * @return The value.
      */
    public boolean getIsOccupied() {
      return isOccupied;
    }


    /**
      * Sets the value of the 'isOccupied' field.
      * @param value The value of 'isOccupied'.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder setIsOccupied(boolean value) {
      validate(fields()[2], value);
      this.isOccupied = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'isOccupied' field has been set.
      * @return True if the 'isOccupied' field has been set, false otherwise.
      */
    public boolean hasIsOccupied() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'isOccupied' field.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder clearIsOccupied() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'components' field.
      * @return The value.
      */
    public java.util.List<org.simulator.dto.ComponentState> getComponents() {
      return components;
    }


    /**
      * Sets the value of the 'components' field.
      * @param value The value of 'components'.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder setComponents(java.util.List<org.simulator.dto.ComponentState> value) {
      validate(fields()[3], value);
      this.components = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'components' field has been set.
      * @return True if the 'components' field has been set, false otherwise.
      */
    public boolean hasComponents() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'components' field.
      * @return This builder.
      */
    public org.simulator.dto.SimulatorState.Builder clearComponents() {
      components = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SimulatorState build() {
      try {
        SimulatorState record = new SimulatorState();
        record.id = fieldSetFlags()[0] ? this.id : (String) defaultValue(fields()[0]);
        record.isActive = fieldSetFlags()[1] ? this.isActive : (Boolean) defaultValue(fields()[1]);
        record.isOccupied = fieldSetFlags()[2] ? this.isOccupied : (Boolean) defaultValue(fields()[2]);
        record.components = fieldSetFlags()[3] ? this.components : (java.util.List<org.simulator.dto.ComponentState>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SimulatorState>
    WRITER$ = (org.apache.avro.io.DatumWriter<SimulatorState>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SimulatorState>
    READER$ = (org.apache.avro.io.DatumReader<SimulatorState>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeBoolean(this.isActive);

    out.writeBoolean(this.isOccupied);

    long size0 = this.components.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (org.simulator.dto.ComponentState e0: this.components) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.isActive = in.readBoolean();

      this.isOccupied = in.readBoolean();

      long size0 = in.readArrayStart();
      java.util.List<org.simulator.dto.ComponentState> a0 = this.components;
      if (a0 == null) {
        a0 = new SpecificData.Array<org.simulator.dto.ComponentState>((int)size0, SCHEMA$.getField("components").schema());
        this.components = a0;
      } else a0.clear();
      SpecificData.Array<org.simulator.dto.ComponentState> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<org.simulator.dto.ComponentState>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          org.simulator.dto.ComponentState e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new org.simulator.dto.ComponentState();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.isActive = in.readBoolean();
          break;

        case 2:
          this.isOccupied = in.readBoolean();
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<org.simulator.dto.ComponentState> a0 = this.components;
          if (a0 == null) {
            a0 = new SpecificData.Array<org.simulator.dto.ComponentState>((int)size0, SCHEMA$.getField("components").schema());
            this.components = a0;
          } else a0.clear();
          SpecificData.Array<org.simulator.dto.ComponentState> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<org.simulator.dto.ComponentState>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              org.simulator.dto.ComponentState e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new org.simulator.dto.ComponentState();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










